var cfg ={};
cfg.secret = process.env.APP_SECRET || 'keyboard cat';

// this is authy key which is generated by creating the application in authy this is required for using the authy rest api.
cfg.authykey = 'RwqD79DgDibEtKdT62m6hv6uxM8BOTRy';

cfg.accountSid = 'AC0bfbebec729e2578b8329d7c53aa9ad6';

cfg.authToken = 'd748074d3af247b1612e4a72ed2ea172';

cfg.twilioNumber = '+16576663567';


module.exports = cfg;